name: remeshing
channels:
  - conda-forge
dependencies:
  - meshio=5.3
  - numpy=1.22
  - pandas=1.2
  - pip=22.1
  - pygalmesh=0.10
  - python=3.9
  - pyyaml=6.0
  - pip:
    - pymeshlab==2022.2
    - optimesh==0.9.4